version: "3.9"

x-user: &user
  root
x-password: &password
  root
x-db: &db
  app

x-conf: &conf
  image: mongo:5.0.7
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: *user
    MONGO_INITDB_ROOT_PASSWORD: *password
    MONGO_INITDB_DATABASE: *db
  command: --keyFile /etc/replicaset.key --replSet rs0

services:
  mongo-primary:
    ports: 
      - "27017:27017"
    volumes:
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./docker/mongo/replicaset.key:/etc/replicaset.key
    <<: *conf

  mongo-secondary:
    ports: 
      - "27018:27017"
    volumes:
      - ./docker/mongo/replicaset.key:/etc/replicaset.key
    <<: *conf

  mongo-tertiary:
    ports:
      - "27019:27017"
    volumes:
      - ./docker/mongo/replicaset.key:/etc/replicaset.key
    <<: *conf

  mongo-arbiter:
    ports:
      - 27020:27017
    volumes:
      - ./docker/mongo/replicaset.key:/etc/replicaset.key
    <<: *conf

  api:
    image: python:3.9-bullseye
    tty: true
    container_name: api
    ports:
      - 8181:8181
    volumes:
      - ./:/app
      - ${HOME}/.aws:/root/.aws
    working_dir: /app
    command: bash
      
